spring:
  profiles:
    # demo: 演示环境，内置数据库；pro 生产环境，mysql数据库
    active: ${active:pro}
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: ${ddl-auto:create}
    show-sql: ${show-sql:false}

server:
  # 配置端口
  port: ${port:8081}
  servlet:
    session:
      timeout: 60m
app:
  # 32 位随机字符串 ASE 密钥
  crypto: ${crypto:gllwmmds4cv1d678azj8plk4sypv35yn}
  # 短消息类型
  sms-type: ${sms-type:local}
  # 初始化管理员用户名
  username: ${default-username:13920618851}
  # 初始化管理员密码
  password: ${default-password:admin}
  # 手机号登录成功后无需再次获取验证码的时间间隔
  timeout: ${effective-timeout:3600}
  #  短信平台
  sms:
    access-key-id: 8TkA3lc5Vo8ub2Cj
    access-secret: 3Q7OleKWhQuDlWPJ3rrXCkO3iYKAzj
    sign-name: 金耕科技
  # token 用于超级验证码的校验
  token: switchgear-
---

logging:
  level:
    club:
      yunzhi:
        switchgear:
          service: debug
    root: info

# 公众号配置(必填)
wx:
  miniapp:
    appid: ${appid:wx27211258368ef97d}
    secret: ${secret:038f9fdc2d248f3fac07ce1c7613cb32}
    token: yunzhi
    aesKey:
    msgDataFormat: json

---
spring:
  config:
    activate:
      on-profile: pro
  jpa:
    hibernate:
      ddl-auto: ${ddl-auto:update}
  flyway:
    enabled: false
  # 配置数据源
  datasource:
    url: jdbc:mysql://${datasource.url:localhost}:${datasource.port:3306}/${datasource.dbname:switchgear}?useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: ${datasource.username:root}
    password: ${datasource.password:}

---
spring:
  config:
    activate:
      on-profile: dev-pj
  jpa:
    hibernate:
      ddl-auto: ${ddl-auto:update}
  flyway:
    enabled: false
  # 配置数据源
  datasource:
    url: jdbc:mysql://${datasource.url:192.168.0.3}:${datasource.port:3633}/${datasource.dbname:switchgear}?useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: ${datasource.username:root}
    password: ${datasource.password:yunzhi.club}
---
spring:
  config:
    activate:
      on-profile: demo
  jpa:
    hibernate:
      ddl-auto: ${ddl-auto:create}
  flyway:
    enabled: false
  # H2数据源,请在当前用户所有文件夹下建立h2-data文件夹，并保证其可写
  # 或者自行指定其它文件位置
  datasource:
    url: jdbc:h2:~/h2-data/switchgear
